export const GET_RESTAURANT_ORDERS_REQUEST = "GET_RESTAURANT_ORDERS_REQUEST";
export const GET_RESTAURANT_ORDERS_SUCCESS = "GET_RESTAURANT_ORDERS_SUCCESS";
export const GET_RESTAURANT_ORDERS_FAILURE = "GET_RESTAURANT_ORDERS_FAILURE";

export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAILURE = "UPDATE_ORDER_STATUS_FAILURE";

export const FILTER_ORDERS_REQUEST = "FILTER_ORDERS_REQUEST";
export const FILTER_ORDERS_SUCCESS = "FILTER_ORDERS_SUCCESS";
export const FILTER_ORDERS_FAILURE = "FILTER_ORDERS_FAILURE";